### ISSUE TITLE
多个服务之间可以嵌套吗

### ISSUE THREAD

**Issue by itmanyong** [ralliejs/rallie#36]
没有基座和子应用的概念，意味着所有应用都是平级的。看到demo的index.html文件都是默认了应用挂载DOM的节点。
那么：
1.如果A应用下面某个路由在页面内需要显示B应用,是否支持呢，因为此刻的B应用挂载的节点应该是由A应用动态生成的而非写在html中的。

**Comment by run-nan** [comment]
可以嵌套的，你说的这种场景代码可以这么写：
**应用B：**
```js
import { createBlock, registerBlock } from 'rallie'
import ReactDOM from 'react-dom'

const b = createBlock('b')

registerBlock(b).onActivate((container) => { // 挂载点从回调参数中拿
     ReactDOM.render(<App />, container)
})
```
**应用A：**
```js
import { createBlock, registerBlock } from 'rallie'

const a = createBlock('a')

// ...省略注册a，以及声明b的路径的代码

a.activate('b',  document.getElementById('b-container')) // 激活b时传递挂载点
```
其实demo里我也是这么写的，只不过做了一个默认值处理而已：
https://github.com/ralliejs/rallie/blob/526c28e58604f2278acee490aebee1fcc1c22d91/packages/playground/apps/react-app/lifecycles.tsx#L7

更详细的说明可以参考文档的生命周期章节：https://rallie.js.cool/guide/advance.html#%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F

**Comment by itmanyong** [comment]
感谢解答

**Comment by run-nan** [comment]
你好，我已收到您的邮件
